/*
    Local sample catalog — DEMO / DEV DATA ONLY
    -------------------------------------------
    Bulk catalog data (100 authors, 127 books) for local development and demos.

    This is NOT schema and NOT reference data:
      - It lives under Scripts/**, which the .sqlproj removes from Build
        (<Build Remove="Scripts/**/*.sql" />) and does NOT declare as <PostDeploy>.
      - Therefore it never enters the DACPAC and never runs on deploy/publish.
        It is opt-in and run by hand against a local database.

    Idempotent: uses MERGE + IDENTITY_INSERT, so it can be re-run safely and keeps
    Ids stable (Books.AuthorId references Authors.Id). Includes the 3 baseline rows
    already seeded by the post-deploy script (Ids 1-3) so it is self-contained.

    How to run (pick one):
      - Via the read-write MCP server (mssql-write): mssql_run_sql_query with this file's content.
      - Via sqlcmd:  sqlcmd -S localhost -U sa -P '***' -d PlaygroundDatabase -i database/Scripts/Local/sample-catalog.sql
*/

PRINT N'Seeding local sample catalog (Authors, Books)...';

SET IDENTITY_INSERT [dbo].[Authors] ON;

MERGE INTO [dbo].[Authors] AS [target]
USING (VALUES
    (1,   'Dino Buzzati'),
    (2,   'Franz Kafka'),
    (3,   'Herman Melville'),
    (4,   'Italo Calvino'),
    (5,   'Umberto Eco'),
    (6,   'Primo Levi'),
    (7,   'Cesare Pavese'),
    (8,   'Elsa Morante'),
    (9,   'Alberto Moravia'),
    (10,  'Luigi Pirandello'),
    (11,  'Giovanni Verga'),
    (12,  'Italo Svevo'),
    (13,  'Gabriel García Márquez'),
    (14,  'Jorge Luis Borges'),
    (15,  'Julio Cortázar'),
    (16,  'Mario Vargas Llosa'),
    (17,  'Pablo Neruda'),
    (18,  'Isabel Allende'),
    (19,  'Fyodor Dostoevsky'),
    (20,  'Leo Tolstoy'),
    (21,  'Anton Chekhov'),
    (22,  'Nikolai Gogol'),
    (23,  'Vladimir Nabokov'),
    (24,  'Mikhail Bulgakov'),
    (25,  'Aleksandr Solzhenitsyn'),
    (26,  'George Orwell'),
    (27,  'Aldous Huxley'),
    (28,  'Virginia Woolf'),
    (29,  'James Joyce'),
    (30,  'Charles Dickens'),
    (31,  'Jane Austen'),
    (32,  'Emily Brontë'),
    (33,  'Charlotte Brontë'),
    (34,  'Oscar Wilde'),
    (35,  'Joseph Conrad'),
    (36,  'Thomas Hardy'),
    (37,  'D.H. Lawrence'),
    (38,  'Mary Shelley'),
    (39,  'Bram Stoker'),
    (40,  'Lewis Carroll'),
    (41,  'Ernest Hemingway'),
    (42,  'F. Scott Fitzgerald'),
    (43,  'William Faulkner'),
    (44,  'John Steinbeck'),
    (45,  'Mark Twain'),
    (46,  'Edgar Allan Poe'),
    (47,  'Nathaniel Hawthorne'),
    (48,  'Henry James'),
    (49,  'J.D. Salinger'),
    (50,  'Jack Kerouac'),
    (51,  'Kurt Vonnegut'),
    (52,  'Ray Bradbury'),
    (53,  'Philip K. Dick'),
    (54,  'Isaac Asimov'),
    (55,  'Arthur C. Clarke'),
    (56,  'Ursula K. Le Guin'),
    (57,  'Frank Herbert'),
    (58,  'J.R.R. Tolkien'),
    (59,  'C.S. Lewis'),
    (60,  'George R.R. Martin'),
    (61,  'Stephen King'),
    (62,  'Cormac McCarthy'),
    (63,  'Toni Morrison'),
    (64,  'Don DeLillo'),
    (65,  'Thomas Pynchon'),
    (66,  'Philip Roth'),
    (67,  'Saul Bellow'),
    (68,  'John Updike'),
    (69,  'Joyce Carol Oates'),
    (70,  'Margaret Atwood'),
    (71,  'Alice Munro'),
    (72,  'Marcel Proust'),
    (73,  'Victor Hugo'),
    (74,  'Gustave Flaubert'),
    (75,  'Albert Camus'),
    (76,  'Jean-Paul Sartre'),
    (77,  'Voltaire'),
    (78,  'Émile Zola'),
    (79,  'Stendhal'),
    (80,  'Honoré de Balzac'),
    (81,  'Alexandre Dumas'),
    (82,  'Antoine de Saint-Exupéry'),
    (83,  'Johann Wolfgang von Goethe'),
    (84,  'Thomas Mann'),
    (85,  'Hermann Hesse'),
    (86,  'Bertolt Brecht'),
    (87,  'Rainer Maria Rilke'),
    (88,  'Günter Grass'),
    (89,  'Miguel de Cervantes'),
    (90,  'Federico García Lorca'),
    (91,  'José Saramago'),
    (92,  'Fernando Pessoa'),
    (93,  'Haruki Murakami'),
    (94,  'Yukio Mishima'),
    (95,  'Yasunari Kawabata'),
    (96,  'Kazuo Ishiguro'),
    (97,  'Salman Rushdie'),
    (98,  'Chinua Achebe'),
    (99,  'Naguib Mahfouz'),
    (100, 'Khaled Hosseini')
) AS [source] ([Id], [FullName])
    ON [target].[Id] = [source].[Id]
WHEN MATCHED THEN
    UPDATE SET [target].[FullName] = [source].[FullName]
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([Id], [FullName]) VALUES ([source].[Id], [source].[FullName]);

SET IDENTITY_INSERT [dbo].[Authors] OFF;

SET IDENTITY_INSERT [dbo].[Books] ON;

MERGE INTO [dbo].[Books] AS [target]
USING (VALUES
    (1,   N'Il deserto dei tartari',                          1),
    (2,   N'Il processo',                                     2),
    (3,   N'Moby Dick',                                       3),
    (4,   N'Il barone rampante',                              4),
    (5,   N'Le città invisibili',                             4),
    (6,   N'Il nome della rosa',                              5),
    (7,   N'Il pendolo di Foucault',                          5),
    (8,   N'Se questo è un uomo',                             6),
    (9,   N'La tregua',                                       6),
    (10,  N'La luna e i falò',                                7),
    (11,  N'La Storia',                                       8),
    (12,  N'L''isola di Arturo',                              8),
    (13,  N'Gli indifferenti',                                9),
    (14,  N'La ciociara',                                     9),
    (15,  N'Il fu Mattia Pascal',                             10),
    (16,  N'Uno, nessuno e centomila',                        10),
    (17,  N'I Malavoglia',                                    11),
    (18,  N'La coscienza di Zeno',                            12),
    (19,  N'Cent''anni di solitudine',                        13),
    (20,  N'L''amore ai tempi del colera',                    13),
    (21,  N'Finzioni',                                        14),
    (22,  N'L''Aleph',                                        14),
    (23,  N'Rayuela',                                         15),
    (24,  N'La città e i cani',                               16),
    (25,  N'Venti poesie d''amore e una canzone disperata',   17),
    (26,  N'La casa degli spiriti',                           18),
    (27,  N'Delitto e castigo',                               19),
    (28,  N'I fratelli Karamazov',                            19),
    (29,  N'Guerra e pace',                                   20),
    (30,  N'Anna Karenina',                                   20),
    (31,  N'Il giardino dei ciliegi',                         21),
    (32,  N'Le anime morte',                                  22),
    (33,  N'Lolita',                                          23),
    (34,  N'Il maestro e Margherita',                         24),
    (35,  N'Arcipelago Gulag',                                25),
    (36,  N'1984',                                            26),
    (37,  N'La fattoria degli animali',                       26),
    (38,  N'Il mondo nuovo',                                  27),
    (39,  N'Gita al faro',                                    28),
    (40,  N'La signora Dalloway',                             28),
    (41,  N'Ulisse',                                          29),
    (42,  N'Gente di Dublino',                                29),
    (43,  N'Grandi speranze',                                 30),
    (44,  N'David Copperfield',                               30),
    (45,  N'Orgoglio e pregiudizio',                          31),
    (46,  N'Emma',                                            31),
    (47,  N'Cime tempestose',                                 32),
    (48,  N'Jane Eyre',                                       33),
    (49,  N'Il ritratto di Dorian Gray',                      34),
    (50,  N'Cuore di tenebra',                                35),
    (51,  N'Tess dei d''Urberville',                          36),
    (52,  N'L''amante di Lady Chatterley',                    37),
    (53,  N'Frankenstein',                                    38),
    (54,  N'Dracula',                                         39),
    (55,  N'Alice nel paese delle meraviglie',                40),
    (56,  N'Il vecchio e il mare',                            41),
    (57,  N'Addio alle armi',                                 41),
    (58,  N'Il grande Gatsby',                                42),
    (59,  N'L''urlo e il furore',                             43),
    (60,  N'Furore',                                          44),
    (61,  N'Uomini e topi',                                   44),
    (62,  N'Le avventure di Huckleberry Finn',                45),
    (63,  N'Il corvo',                                        46),
    (64,  N'La lettera scarlatta',                            47),
    (65,  N'Ritratto di signora',                             48),
    (66,  N'Il giovane Holden',                               49),
    (67,  N'Sulla strada',                                    50),
    (68,  N'Mattatoio n. 5',                                  51),
    (69,  N'Fahrenheit 451',                                  52),
    (70,  N'Cronache marziane',                               52),
    (71,  N'Ma gli androidi sognano pecore elettriche?',      53),
    (72,  N'Io, robot',                                       54),
    (73,  N'Fondazione',                                      54),
    (74,  N'2001: Odissea nello spazio',                      55),
    (75,  N'La mano sinistra delle tenebre',                  56),
    (76,  N'Dune',                                            57),
    (77,  N'Il Signore degli Anelli',                         58),
    (78,  N'Lo Hobbit',                                       58),
    (79,  N'Le cronache di Narnia',                           59),
    (80,  N'Il Trono di Spade',                               60),
    (81,  N'It',                                              61),
    (82,  N'Shining',                                         61),
    (83,  N'La strada',                                       62),
    (84,  N'Non è un paese per vecchi',                       62),
    (85,  N'Amatissima',                                      63),
    (86,  N'Rumore bianco',                                   64),
    (87,  N'L''arcobaleno della gravità',                     65),
    (88,  N'Pastorale americana',                             66),
    (89,  N'Herzog',                                          67),
    (90,  N'Corri, Coniglio',                                 68),
    (91,  N'Blonde',                                          69),
    (92,  N'Il racconto dell''ancella',                       70),
    (93,  N'In fuga',                                         71),
    (94,  N'Alla ricerca del tempo perduto',                  72),
    (95,  N'I miserabili',                                    73),
    (96,  N'Notre-Dame de Paris',                             73),
    (97,  N'Madame Bovary',                                   74),
    (98,  N'Lo straniero',                                    75),
    (99,  N'La peste',                                        75),
    (100, N'La nausea',                                       76),
    (101, N'Candido',                                         77),
    (102, N'Germinale',                                       78),
    (103, N'Il rosso e il nero',                              79),
    (104, N'Papà Goriot',                                     80),
    (105, N'Il conte di Montecristo',                         81),
    (106, N'I tre moschettieri',                              81),
    (107, N'Il piccolo principe',                             82),
    (108, N'I dolori del giovane Werther',                    83),
    (109, N'La montagna incantata',                           84),
    (110, N'Siddharta',                                       85),
    (111, N'Il lupo della steppa',                            85),
    (112, N'L''opera da tre soldi',                           86),
    (113, N'Elegie duinesi',                                  87),
    (114, N'Il tamburo di latta',                             88),
    (115, N'Don Chisciotte della Mancia',                     89),
    (116, N'Nozze di sangue',                                 90),
    (117, N'Cecità',                                          91),
    (118, N'Il libro dell''inquietudine',                     92),
    (119, N'Norwegian Wood',                                  93),
    (120, N'1Q84',                                            93),
    (121, N'Il padiglione d''oro',                            94),
    (122, N'Il paese delle nevi',                             95),
    (123, N'Quel che resta del giorno',                       96),
    (124, N'I figli della mezzanotte',                        97),
    (125, N'Il crollo',                                       98),
    (126, N'Vicolo del Mortaio',                              99),
    (127, N'Il cacciatore di aquiloni',                       100)
) AS [source] ([Id], [Title], [AuthorId])
    ON [target].[Id] = [source].[Id]
WHEN MATCHED THEN
    UPDATE SET [target].[Title]    = [source].[Title],
               [target].[AuthorId] = [source].[AuthorId]
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([Id], [Title], [AuthorId])
    VALUES ([source].[Id], [source].[Title], [source].[AuthorId]);

SET IDENTITY_INSERT [dbo].[Books] OFF;

PRINT N'Local sample catalog seeded.';
